[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
gig_basic_contract = "6i7THycw37PvBMKPuC8gTD5GjdUeJ5XcWL5Y3Q7FrRtR"

[programs.localnet]
gig_basic_contract = "6i7THycw37PvBMKPuC8gTD5GjdUeJ5XcWL5Y3Q7FrRtR"

[programs.mainnet]
gig_basic_contract = "6i7THycw37PvBMKPuC8gTD5GjdUeJ5XcWL5Y3Q7FrRtR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/kkr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
