[features]
seeds = false
skip-lint = false

[programs.localnet]
gig_basic_contract = "FjPwNzWH81Gc69RruKgCeu6DZwSdSfDrXdjG84JyNS5e"

[programs.devnet]
gig_basic_contract = "D6a3MwZXtduiRS56F5XGXfSGKkCXxLSbLy7FTVtN4T74"

[programs.mainnet]
gig_basic_contract = "GuqgMVMCLi9daQMHyhnLRGTpgpwNGU4yZXs9GK4SYrbS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/rrr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
