[features]
seeds = false
skip-lint = false

[programs.localnet]
gig_basic_contract = "FjPwNzWH81Gc69RruKgCeu6DZwSdSfDrXdjG84JyNS5e"

[programs.devnet]
gig_basic_contract = "CWSV9rB1AFGXLozdtGaDhi5747rnLA1Gd32eLwL9Nw5R"

[programs.mainnet]
gig_basic_contract = "CWSV9rB1AFGXLozdtGaDhi5747rnLA1Gd32eLwL9Nw5R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/rrr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
